### ISSUE TITLE
Latest update non functional

### ISSUE THREAD

**Issue by codecleric** [soberhacker/obsidian-telegram-sync#221]
I have Obsidian 1.4.16 on Ubuntu 23.04 and Telegram Sync 2.1.0.  The settings pane for the plugin is blank and I see the following in the developer console:

```
Telegram Sync: Error with user connection -> Unhandled error while receiving data
plugin:telegram-sync:97614 Telegram Sync: Error with user connection -> TypeError: Argument must be a Buffer
plugin:telegram-sync:25148 Error: WebSocket was closed
    at node_modules/telegram/extensions/PromisedWebSockets.js (plugin:telegram-sync:17225:22)
    at __require (plugin:telegram-sync:16:51)
    at node_modules/telegram/extensions/index.js (plugin:telegram-sync:20260:32)
    at __require (plugin:telegram-sync:16:51)
    at node_modules/telegram/network/connection/Connection.js (plugin:telegram-sync:20513:24)
    at __require (plugin:telegram-sync:16:51)
    at node_modules/telegram/network/connection/index.js (plugin:telegram-sync:21238:24)
    at __require (plugin:telegram-sync:16:51)
    at node_modules/telegram/client/telegramBaseClient.js (plugin:telegram-sync:25376:24)
    at __require (plugin:telegram-sync:16:51)
    at node_modules/telegram/client/TelegramClient.js (plugin:telegram-sync:29235:32)
    at __require (plugin:telegram-sync:16:51)
    at node_modules/telegram/index.js (plugin:telegram-sync:30495:28)
    at __require (plugin:telegram-sync:16:51)
    at anonymous (plugin:telegram-sync:96893:32)
    at e.<anonymous> (app.js:1:2037091)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at a (app.js:1:235850)
_tryConnect @ plugin:telegram-sync:25148
DevTools failed 
```

**Comment by soberhacker** [comment]
Hi
What was the reason?

Thanks

**Comment by codecleric** [comment]
I have no idea, the problem just went away an the plugin interface started working again. Currently, it seems to be having trouble connecting to the telegram API, but that may be a telegram problem, not a plugin problem.
